version: '3.1'

services:

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: citus
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: EPP@ss#1

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
